export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'

export const ADD_TO_CART = 'ADD_TO_CART'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ADD_REVIEW = 'ADD_REVIEW'

export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS'

export const FETCH_DISHES = 'FETCH_DISHES'

export const FETCH_REVIEWS = 'FETCH_REVIEWS'
